### ISSUE TITLE
Not working with crosswalk

### ISSUE THREAD

**Issue by do-web** [appfeel/admob-google-cordova#20]

**Comment by wasa4587** [comment]
This doesn't works after add this pluggin
```
UNEXPECTED TOP-LEVEL ERROR:
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
        at java.lang.String.<init>(String.java:207)
        at java.lang.String.substring(String.java:1933)
        at com.android.dx.rop.type.Prototype.withFirstParameter(Prototype.java:3
70)
        at com.android.dx.rop.type.Prototype.intern(Prototype.java:180)
        at com.android.dx.cf.iface.StdMethod.<init>(StdMethod.java:46)
        at com.android.dx.cf.direct.MethodListParser.set(MethodListParser.java:8
1)
        at com.android.dx.cf.direct.MemberListParser.parse(MemberListParser.java
:217)
        at com.android.dx.cf.direct.MemberListParser.parseIfNecessary(MemberList
Parser.java:108)
        at com.android.dx.cf.direct.MethodListParser.getList(MethodListParser.ja
va:54)
        at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:
551)
        at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:4
06)
        at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary
(DirectClassFile.java:388)
        at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.jav
a:251)
        at com.android.dx.command.dexer.Main.parseClass(Main.java:772)
        at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
        at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1700
)
        at com.android.dx.command.dexer.Main.processClass(Main.java:755)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:723)
        at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
        at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(
Main.java:1653)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpen
er.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.j
ava:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java
:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:677)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:569)
        at com.android.dx.command.dexer.Main.runMultiDex(Main.java:366)
        at com.android.dx.command.dexer.Main.run(Main.java:275)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForArmv7Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.pro
cess.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.
common.process.ProcessException: org.gradle.process.internal.ExecException: Proc
ess 'command 'C:\Program Files\Java\jdk1.8.0_101\bin\java.exe'' finished with no
n-zero exit value 3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.
```
