### ISSUE TITLE
com.google.firebase not found on logcat

### ISSUE THREAD

**Issue by wasa4587** [appfeel/admob-google-cordova#55]
````
java.lang.NoClassDefFoundError: com.google.firebase.FirebaseOptions
E/AndroidRuntime( 2880):        at com.google.firebase.FirebaseApp.zzek(UnknownSource)
E/AndroidRuntime( 2880):        at com.google.firebase.provider.FirebaseInitProvider.onCreate(UnknownSource)E/AndroidRuntime( 2880):        at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
E/AndroidRuntime( 2880):        at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
E/AndroidRuntime( 2880):        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
E/AndroidRuntime( 2880):        at android.app.ActivityThread.installProvider(ActivityThread.java:5233)
E/AndroidRuntime( 2880):        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4828)
E/AndroidRuntime( 2880):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4711)
E/AndroidRuntime( 2880):        at android.app.ActivityThread.access$1600(ActivityThread.java:175)
E/AndroidRuntime( 2880):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
E/AndroidRuntime( 2880):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2880):        at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime( 2880):        at android.app.ActivityThread.main(ActivityThread.java:5602)
E/AndroidRuntime( 2880):        at java.lang.reflect.Method.invokeNative(NativeMethod)
E/AndroidRuntime( 2880):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2880):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/AndroidRuntime( 2880):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/AndroidRuntime( 2880):        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by appfeel** [comment]
Fixed on https://github.com/appfeel/admob-google-cordova/pull/56
